pipeline {
    agent any

    environment {
        registry = "astoiculescu/simple-java-maven-app"
        registryCredential = 'Docker-Hub'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
		sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Build docker image') {
	    steps {
                sh "docker ps"
            }	
        }
    }
}
